# Config
dist: xenial
language: rust

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

# Matrix
matrix:
  include:
    # Linux Qt 5
    - os: linux
      env: QT_SELECT=5
      rust: stable

    - os: linux
      env: QT_SELECT=5
      rust: beta

    - os: linux
      env: QT_SELECT=5
      rust: nightly

    # Linux Qt 4
    - os: linux
      env: QT_SELECT=4
      rust: stable

    # Linux Qt 5 manual
    - os: linux
      env: QT_INSTALL_DIR=/usr/lib/x86_64-linux-gnu/qt5
      rust: stable

    # OSX Qt 5
    - os: osx
      rust: stable

    - os: osx
      rust: beta

    - os: osx
      rust: nightly

    # OSX Qt 5 manual
    - os: osx
      env: QT_INSTALL_DIR=/usr/local/opt/qt
      rust: stable

  allow_failures:
    - rust: nightly

# Pipeline
before_install:
  - bash ci/before_install.sh

script:
  - bash ci/script.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

# Notifications
notifications:
  email:

on_success: never

# Cache
cache:
  - cargo
