[package]
name = "qt-auto-binding-core"
version = "0.1.0"
authors = ["Lucien XU <sfietkonstantin@free.fr>"]

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"

[features]
nightly = ["proc-macro2/nightly"]