[package]
name = "qt-sys"
version = "0.1.0"
authors = ["Lucien XU <sfietkonstantin@free.fr>"]
edition = "2018"
build = "build.rs"
links = "qt"

[build-dependencies]
qt-locate = {path = "../qt-locate"}

[features]
gui = []
qml = ["gui"]
quick = ["qml"]
