[package]
name = "qt-binding-build"
version = "0.1.0"
authors = ["Lucien XU <sfietkonstantin@free.fr>"]
edition = "2018"

[dependencies]
cc = "1.0"
qt-install = {path = "../qt-install"}

[features]
gui = []
qml = ["gui"]
quick = ["qml"]
widgets = ["gui"]